# Generated by Django 3.2 on 2021-05-10 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='db_null',
            field=models.IntegerField(null=True),
        ),
    ]
